# Generated by Django 4.2.6 on 2024-01-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('disponibilidade', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado')], max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='appSGB.autor')),
            ],
        ),
    ]
