version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: new_bd
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: new_password
    ports:
      - "5439:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8070:80"
    depends_on:
      - db
